// Code generated by protoc-gen-go. DO NOT EDIT.
// source: converter.proto

package converter

import (
	context "context"
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type ConversionRequest struct {
	Source               string   `protobuf:"bytes,1,opt,name=source,proto3" json:"source,omitempty"`
	Target               string   `protobuf:"bytes,2,opt,name=target,proto3" json:"target,omitempty"`
	Amount               float32  `protobuf:"fixed32,3,opt,name=amount,proto3" json:"amount,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ConversionRequest) Reset()         { *m = ConversionRequest{} }
func (m *ConversionRequest) String() string { return proto.CompactTextString(m) }
func (*ConversionRequest) ProtoMessage()    {}
func (*ConversionRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_c03eb4403ca9b02d, []int{0}
}

func (m *ConversionRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ConversionRequest.Unmarshal(m, b)
}
func (m *ConversionRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ConversionRequest.Marshal(b, m, deterministic)
}
func (m *ConversionRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ConversionRequest.Merge(m, src)
}
func (m *ConversionRequest) XXX_Size() int {
	return xxx_messageInfo_ConversionRequest.Size(m)
}
func (m *ConversionRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_ConversionRequest.DiscardUnknown(m)
}

var xxx_messageInfo_ConversionRequest proto.InternalMessageInfo

func (m *ConversionRequest) GetSource() string {
	if m != nil {
		return m.Source
	}
	return ""
}

func (m *ConversionRequest) GetTarget() string {
	if m != nil {
		return m.Target
	}
	return ""
}

func (m *ConversionRequest) GetAmount() float32 {
	if m != nil {
		return m.Amount
	}
	return 0
}

// The response message containing the greetings
type ConversionReply struct {
	Amount               float32  `protobuf:"fixed32,1,opt,name=amount,proto3" json:"amount,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ConversionReply) Reset()         { *m = ConversionReply{} }
func (m *ConversionReply) String() string { return proto.CompactTextString(m) }
func (*ConversionReply) ProtoMessage()    {}
func (*ConversionReply) Descriptor() ([]byte, []int) {
	return fileDescriptor_c03eb4403ca9b02d, []int{1}
}

func (m *ConversionReply) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ConversionReply.Unmarshal(m, b)
}
func (m *ConversionReply) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ConversionReply.Marshal(b, m, deterministic)
}
func (m *ConversionReply) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ConversionReply.Merge(m, src)
}
func (m *ConversionReply) XXX_Size() int {
	return xxx_messageInfo_ConversionReply.Size(m)
}
func (m *ConversionReply) XXX_DiscardUnknown() {
	xxx_messageInfo_ConversionReply.DiscardUnknown(m)
}

var xxx_messageInfo_ConversionReply proto.InternalMessageInfo

func (m *ConversionReply) GetAmount() float32 {
	if m != nil {
		return m.Amount
	}
	return 0
}

func init() {
	proto.RegisterType((*ConversionRequest)(nil), "converter.ConversionRequest")
	proto.RegisterType((*ConversionReply)(nil), "converter.ConversionReply")
}

func init() {
	proto.RegisterFile("converter.proto", fileDescriptor_c03eb4403ca9b02d)
}

var fileDescriptor_c03eb4403ca9b02d = []byte{
	// 196 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0xe2, 0x4f, 0xce, 0xcf, 0x2b,
	0x4b, 0x2d, 0x2a, 0x49, 0x2d, 0xd2, 0x2b, 0x28, 0xca, 0x2f, 0xc9, 0x17, 0xe2, 0x84, 0x0b, 0x28,
	0x45, 0x73, 0x09, 0x3a, 0x83, 0x39, 0xc5, 0x99, 0xf9, 0x79, 0x41, 0xa9, 0x85, 0xa5, 0xa9, 0xc5,
	0x25, 0x42, 0x62, 0x5c, 0x6c, 0xc5, 0xf9, 0xa5, 0x45, 0xc9, 0xa9, 0x12, 0x8c, 0x0a, 0x8c, 0x1a,
	0x9c, 0x41, 0x50, 0x1e, 0x48, 0xbc, 0x24, 0xb1, 0x28, 0x3d, 0xb5, 0x44, 0x82, 0x09, 0x22, 0x0e,
	0xe1, 0x81, 0xc4, 0x13, 0x73, 0xf3, 0x4b, 0xf3, 0x4a, 0x24, 0x98, 0x15, 0x18, 0x35, 0x98, 0x82,
	0xa0, 0x3c, 0x25, 0x4d, 0x2e, 0x7e, 0x64, 0xc3, 0x0b, 0x72, 0x2a, 0x91, 0x94, 0x32, 0x22, 0x2b,
	0x35, 0x8a, 0xe0, 0xe2, 0x74, 0x86, 0x39, 0x4a, 0xc8, 0x9b, 0x8b, 0xd7, 0x3d, 0xb5, 0x04, 0xa1,
	0x55, 0x48, 0x46, 0x0f, 0xe1, 0x05, 0x0c, 0xe7, 0x4a, 0x49, 0xe1, 0x90, 0x2d, 0xc8, 0xa9, 0x54,
	0x62, 0x70, 0xd2, 0xe3, 0x92, 0xca, 0xcc, 0xd7, 0x4b, 0x2f, 0x2a, 0x48, 0xd6, 0x4b, 0xad, 0x48,
	0xcc, 0x2d, 0xc8, 0x49, 0x2d, 0x46, 0xa8, 0x77, 0xe2, 0x83, 0xdb, 0x1a, 0x00, 0x0a, 0x9a, 0x00,
	0xc6, 0x24, 0x36, 0x70, 0x18, 0x19, 0x03, 0x02, 0x00, 0x00, 0xff, 0xff, 0xe7, 0x70, 0xd6, 0x47,
	0x36, 0x01, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConnInterface

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion6

// ConverterClient is the client API for Converter service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type ConverterClient interface {
	GetConversion(ctx context.Context, in *ConversionRequest, opts ...grpc.CallOption) (*ConversionReply, error)
}

type converterClient struct {
	cc grpc.ClientConnInterface
}

func NewConverterClient(cc grpc.ClientConnInterface) ConverterClient {
	return &converterClient{cc}
}

func (c *converterClient) GetConversion(ctx context.Context, in *ConversionRequest, opts ...grpc.CallOption) (*ConversionReply, error) {
	out := new(ConversionReply)
	err := c.cc.Invoke(ctx, "/converter.Converter/GetConversion", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// ConverterServer is the server API for Converter service.
type ConverterServer interface {
	GetConversion(context.Context, *ConversionRequest) (*ConversionReply, error)
}

// UnimplementedConverterServer can be embedded to have forward compatible implementations.
type UnimplementedConverterServer struct {
}

func (*UnimplementedConverterServer) GetConversion(ctx context.Context, req *ConversionRequest) (*ConversionReply, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetConversion not implemented")
}

func RegisterConverterServer(s *grpc.Server, srv ConverterServer) {
	s.RegisterService(&_Converter_serviceDesc, srv)
}

func _Converter_GetConversion_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ConversionRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ConverterServer).GetConversion(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/converter.Converter/GetConversion",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ConverterServer).GetConversion(ctx, req.(*ConversionRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _Converter_serviceDesc = grpc.ServiceDesc{
	ServiceName: "converter.Converter",
	HandlerType: (*ConverterServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetConversion",
			Handler:    _Converter_GetConversion_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "converter.proto",
}
